In [12]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [13]:
df = pd.read_csv('multi.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [14]:
df.bedrooms.median()

3.5

In [15]:
import math

In [16]:
df = df.fillna(math.floor(df.bedrooms.median()))

In [17]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [18]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [19]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [20]:
reg.intercept_

383725.00000000006

In [21]:
reg.predict([[3000,3,40]])

array([444400.])

In [22]:
reg.predict([[2500,4,5]])

array([588625.])