In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [12]:
from sklearn.datasets import load_digits
digits = load_digits()

In [13]:
from sklearn.model_selection import train_test_split
xtrain , xtest , ytrain , ytest = train_test_split(digits.data , digits.target , train_size = 0.7)

In [14]:
lir = LinearRegression()
lir.fit(xtrain , ytrain)
lir.score(xtest , ytest)

0.5793041589971806

In [15]:
lor = LogisticRegression()
lor.fit(xtrain , ytrain)
lor.score(xtest , ytest)

c:\users\college\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [16]:
svm = SVC()
svm.fit(xtrain , ytrain)
svm.score(xtest , ytest)

0.9962962962962963

In [17]:
dtc = DecisionTreeClassifier()
dtc.fit(xtrain , ytrain)
dtc.score(xtest , ytest)

0.8203703703703704

In [18]:
rfc = RandomForestClassifier()
rfc.fit(xtrain , ytrain)
rfc.score(xtest , ytest)

0.975925925925926

In [37]:
from sklearn.model_selection import StratifiedKFold 
folds = StratifiedKFold(n_splits = 5)

In [38]:
from sklearn.model_selection import cross_val_score

In [39]:
cross_val_score(lir , digits.data , digits.target)

array([0.48346048, 0.5583603 , 0.57534522, 0.5056632 , 0.40995457])

In [40]:
cross_val_score(lor , digits.data , digits.target)

c:\users\college\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\college\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [41]:
cross_val_score(svm , digits.data , digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [42]:
cross_val_score(dtc , digits.data , digits.target)

array([0.76944444, 0.71666667, 0.79108635, 0.83286908, 0.79665738])

In [43]:
cross_val_score(rfc , digits.data , digits.target)

array([0.93888889, 0.925     , 0.96100279, 0.96657382, 0.93593315])